version: "3"
services:
  couper:
    image: coupergateway/couper
    container_name: client
    hostname: client
    ports:
      - 8080:8080
    depends_on:
      - rs
      - as
    volumes:
      - ./client:/conf
    environment:
      # hot reload config
      - COUPER_WATCH=true
  rs:
    image: coupergateway/couper
    container_name: resource-server
    hostname: resource-server
    ports:
      - 8081:8080
    volumes:
      - ./resource-server:/conf
    environment:
      # hot reload config
      - COUPER_WATCH=true
  as:
    image: coupergateway/couper
    container_name: authorization-server
    hostname: authorization-server
    ports:
      - 8082:8080
    volumes:
      - ./authorization-server:/conf
    environment:
      # hot reload config
      - COUPER_WATCH=true
